[package]
name = "beluga"
version = "0.1.1"
description = "A dictionary application"
default-run = "beluga"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6.1", features = [ "shell-all", "dialog-all", "system-tray", "devtools"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"
flate2 = "1.0.28"
anyhow = "1.0.81"
axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["cookie"] }
mime_guess = "2.0.4"
beluga-core = { path = "../beluga-core" }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
