[package]
name = "laputa"
version = "0.1.0"
description = "A dictionary application"
default-run = "laputa"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.5.4", features = [] }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
